"""
tests/test_m3_explanations.py — Sprint M3 Explainability tests.

Covers:
  - ExplanationBuilder.build_pi_explanation produces correct Explanation
  - summary is non-empty
  - causal_path has at least 1 step
  - shortage → explanation auto-generated by propagator (mocked)
  - persist + get_explanation round-trip (mocked DB)
"""
from __future__ import annotations

import uuid
from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Optional
from unittest.mock import MagicMock, call, patch
from uuid import UUID, uuid4

import pytest

from ootils_core.models import (
    CausalStep,
    Edge,
    Explanation,
    Node,
)
from ootils_core.engine.kernel.explanation.builder import ExplanationBuilder


# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

def make_node(
    node_type: str = "ProjectedInventory",
    quantity: Optional[Decimal] = None,
    has_shortage: bool = False,
    shortage_qty: Decimal = Decimal("0"),
    time_ref: Optional[date] = None,
    time_span_start: Optional[date] = None,
    time_span_end: Optional[date] = None,
    node_id: Optional[UUID] = None,
    scenario_id: Optional[UUID] = None,
) -> Node:
    return Node(
        node_id=node_id or uuid4(),
        node_type=node_type,
        scenario_id=scenario_id or uuid4(),
        quantity=quantity,
        has_shortage=has_shortage,
        shortage_qty=shortage_qty,
        time_ref=time_ref,
        time_span_start=time_span_start,
        time_span_end=time_span_end,
    )


def make_edge(
    from_node_id: UUID,
    to_node_id: UUID,
    edge_type: str,
    scenario_id: UUID,
    priority: int = 0,
) -> Edge:
    return Edge(
        edge_id=uuid4(),
        edge_type=edge_type,
        from_node_id=from_node_id,
        to_node_id=to_node_id,
        scenario_id=scenario_id,
        priority=priority,
    )


# ---------------------------------------------------------------------------
# Tests: build_pi_explanation
# ---------------------------------------------------------------------------

class TestBuildPiExplanation:

    def test_returns_explanation_instance(self):
        """build_pi_explanation returns an Explanation."""
        scenario_id = uuid4()
        pi_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            scenario_id=scenario_id,
        )
        demand_node = make_node(
            node_type="CustomerOrderDemand",
            quantity=Decimal("150"),
            time_ref=date(2026, 4, 5),
            scenario_id=scenario_id,
        )
        supply_node = make_node(
            node_type="PurchaseOrderSupply",
            quantity=Decimal("100"),
            time_ref=date(2026, 4, 6),
            scenario_id=scenario_id,
        )

        demand_edge = make_edge(demand_node.node_id, pi_node.node_id, "consumes", scenario_id)
        supply_edge = make_edge(supply_node.node_id, pi_node.node_id, "replenishes", scenario_id)

        store = MagicMock()
        store.get_edges_to.side_effect = lambda node_id, sid, edge_type=None: (
            [demand_edge] if edge_type == "consumes" else [supply_edge]
        )
        store.get_node.side_effect = lambda nid, sid: {
            demand_node.node_id: demand_node,
            supply_node.node_id: supply_node,
        }.get(nid)

        calc_run_id = uuid4()
        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, calc_run_id, store, db=MagicMock())

        assert isinstance(explanation, Explanation)
        assert explanation.calc_run_id == calc_run_id
        assert explanation.target_node_id == pi_node.node_id
        assert explanation.target_type == "Shortage"

    def test_summary_is_non_empty(self):
        """summary must be a non-empty string."""
        scenario_id = uuid4()
        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("30"),
            scenario_id=scenario_id,
        )

        store = MagicMock()
        store.get_edges_to.return_value = []  # no demand, no supply

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        assert explanation.summary
        assert len(explanation.summary) > 0

    def test_causal_path_has_at_least_one_step(self):
        """causal_path must contain at least 1 CausalStep."""
        scenario_id = uuid4()
        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("10"),
            scenario_id=scenario_id,
        )

        store = MagicMock()
        store.get_edges_to.return_value = []

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        assert len(explanation.causal_path) >= 1
        assert all(isinstance(s, CausalStep) for s in explanation.causal_path)

    def test_steps_are_ordered(self):
        """Steps must be numbered sequentially starting from 1."""
        scenario_id = uuid4()
        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("50"),
            scenario_id=scenario_id,
        )
        demand_node = make_node(
            node_type="ForecastDemand",
            quantity=Decimal("200"),
            scenario_id=scenario_id,
        )
        supply_node = make_node(
            node_type="PurchaseOrderSupply",
            quantity=Decimal("150"),
            time_ref=date(2026, 5, 1),
            scenario_id=scenario_id,
        )

        demand_edge = make_edge(demand_node.node_id, pi_node.node_id, "consumes", scenario_id)
        supply_edge = make_edge(supply_node.node_id, pi_node.node_id, "replenishes", scenario_id)

        store = MagicMock()
        store.get_edges_to.side_effect = lambda node_id, sid, edge_type=None: (
            [demand_edge] if edge_type == "consumes" else [supply_edge]
        )
        store.get_node.side_effect = lambda nid, sid: {
            demand_node.node_id: demand_node,
            supply_node.node_id: supply_node,
        }.get(nid)

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        steps = [s.step for s in explanation.causal_path]
        assert steps == sorted(steps)
        assert steps[0] == 1

    def test_delayed_supply_detected_as_root_cause(self):
        """Supply delayed past bucket end → root_cause_node_id set + step 3 mentions delay."""
        scenario_id = uuid4()
        bucket_end = date(2026, 4, 7)
        supply_date = date(2026, 4, 15)  # delayed 8 days past bucket_end

        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("80"),
            time_span_start=date(2026, 4, 1),
            time_span_end=bucket_end,
            scenario_id=scenario_id,
        )
        demand_node = make_node(
            node_type="CustomerOrderDemand",
            quantity=Decimal("100"),
            scenario_id=scenario_id,
        )
        supply_node = make_node(
            node_type="PurchaseOrderSupply",
            quantity=Decimal("100"),
            time_ref=supply_date,
            scenario_id=scenario_id,
        )

        demand_edge = make_edge(demand_node.node_id, pi_node.node_id, "consumes", scenario_id)
        supply_edge = make_edge(supply_node.node_id, pi_node.node_id, "replenishes", scenario_id)

        store = MagicMock()
        store.get_edges_to.side_effect = lambda node_id, sid, edge_type=None: (
            [demand_edge] if edge_type == "consumes" else [supply_edge]
        )
        store.get_node.side_effect = lambda nid, sid: {
            demand_node.node_id: demand_node,
            supply_node.node_id: supply_node,
        }.get(nid)

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        assert explanation.root_cause_node_id == supply_node.node_id
        step3 = next((s for s in explanation.causal_path if s.step == 3), None)
        assert step3 is not None
        assert "delay" in step3.fact.lower() or "delayed" in step3.fact.lower()

    def test_insufficient_supply_detected_as_root_cause(self):
        """Supply qty < shortage qty → root cause is insufficient supply."""
        scenario_id = uuid4()
        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("70"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            scenario_id=scenario_id,
        )
        demand_node = make_node(
            node_type="CustomerOrderDemand",
            quantity=Decimal("100"),
            scenario_id=scenario_id,
        )
        supply_node = make_node(
            node_type="PurchaseOrderSupply",
            quantity=Decimal("30"),  # less than shortage_qty=70
            time_ref=date(2026, 4, 3),  # on time
            scenario_id=scenario_id,
        )

        demand_edge = make_edge(demand_node.node_id, pi_node.node_id, "consumes", scenario_id)
        supply_edge = make_edge(supply_node.node_id, pi_node.node_id, "replenishes", scenario_id)

        store = MagicMock()
        store.get_edges_to.side_effect = lambda node_id, sid, edge_type=None: (
            [demand_edge] if edge_type == "consumes" else [supply_edge]
        )
        store.get_node.side_effect = lambda nid, sid: {
            demand_node.node_id: demand_node,
            supply_node.node_id: supply_node,
        }.get(nid)

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        assert explanation.root_cause_node_id == supply_node.node_id
        step3 = next((s for s in explanation.causal_path if s.step == 3), None)
        assert step3 is not None
        assert "insufficient" in step3.fact.lower()

    def test_no_supply_case(self):
        """No supply edges → steps 2 and 3 mention missing supply."""
        scenario_id = uuid4()
        pi_node = make_node(
            has_shortage=True,
            shortage_qty=Decimal("100"),
            scenario_id=scenario_id,
        )
        demand_node = make_node(
            node_type="ForecastDemand",
            quantity=Decimal("100"),
            scenario_id=scenario_id,
        )
        demand_edge = make_edge(demand_node.node_id, pi_node.node_id, "consumes", scenario_id)

        store = MagicMock()
        store.get_edges_to.side_effect = lambda node_id, sid, edge_type=None: (
            [demand_edge] if edge_type == "consumes" else []
        )
        store.get_node.side_effect = lambda nid, sid: {
            demand_node.node_id: demand_node,
        }.get(nid)

        builder = ExplanationBuilder()
        explanation = builder.build_pi_explanation(pi_node, uuid4(), store, db=MagicMock())

        step3 = next((s for s in explanation.causal_path if s.step == 3), None)
        assert step3 is not None
        assert "missing" in step3.fact.lower() or "uncovered" in step3.fact.lower()


# ---------------------------------------------------------------------------
# Tests: persist + get_explanation round-trip (mocked DB)
# ---------------------------------------------------------------------------

class TestPersistRoundTrip:

    def _make_explanation(self) -> Explanation:
        return Explanation(
            explanation_id=uuid4(),
            calc_run_id=uuid4(),
            target_node_id=uuid4(),
            target_type="Shortage",
            root_cause_node_id=uuid4(),
            causal_path=[
                CausalStep(step=1, node_id=uuid4(), node_type="CustomerOrderDemand",
                           edge_type="consumes", fact="Order requires 100 units"),
                CausalStep(step=2, node_id=uuid4(), node_type="PurchaseOrderSupply",
                           edge_type="replenishes", fact="PO provides 50 units"),
                CausalStep(step=3, node_id=None, node_type="PolicyCheck",
                           edge_type="governed_by", fact="No substitute active"),
            ],
            summary="Order requires 100 units. No substitute active.",
            created_at=datetime.now(timezone.utc),
        )

    def test_persist_calls_db_correctly(self):
        """persist() issues the correct INSERT statements."""
        explanation = self._make_explanation()
        db = MagicMock()

        builder = ExplanationBuilder()
        builder.persist(explanation, db)

        # First call: INSERT INTO explanations
        calls = db.execute.call_args_list
        assert len(calls) == 1 + len(explanation.causal_path)  # 1 header + N steps

        first_call_sql = calls[0][0][0]
        assert "INSERT INTO explanations" in first_call_sql

        # Subsequent calls: INSERT INTO causal_steps
        for i in range(1, len(calls)):
            sql = calls[i][0][0]
            assert "INSERT INTO causal_steps" in sql

    def test_get_explanation_returns_none_when_not_found(self):
        """get_explanation returns None when no row exists."""
        db = MagicMock()
        db.execute.return_value.fetchone.return_value = None

        builder = ExplanationBuilder()
        result = builder.get_explanation(uuid4(), db)

        assert result is None

    def test_get_explanation_reconstructs_from_db(self):
        """get_explanation correctly maps DB rows back to Explanation."""
        explanation_id = uuid4()
        calc_run_id = uuid4()
        target_node_id = uuid4()
        root_cause_id = uuid4()
        step_node_id = uuid4()
        created_at = datetime.now(timezone.utc)

        header_row = {
            "explanation_id": explanation_id,
            "calc_run_id": calc_run_id,
            "target_node_id": target_node_id,
            "target_type": "Shortage",
            "root_cause_node_id": root_cause_id,
            "summary": "Test summary.",
            "created_at": created_at,
        }
        step_rows = [
            {
                "step": 1,
                "node_id": step_node_id,
                "node_type": "CustomerOrderDemand",
                "edge_type": "consumes",
                "fact": "Order requires 50 units",
            },
        ]

        db = MagicMock()
        # First call fetches header row, second fetches steps
        db.execute.return_value.fetchone.return_value = header_row
        db.execute.return_value.fetchall.return_value = step_rows

        builder = ExplanationBuilder()
        result = builder.get_explanation(target_node_id, db)

        assert result is not None
        assert result.explanation_id == explanation_id
        assert result.calc_run_id == calc_run_id
        assert result.target_node_id == target_node_id
        assert result.target_type == "Shortage"
        assert result.root_cause_node_id == root_cause_id
        assert result.summary == "Test summary."
        assert len(result.causal_path) == 1
        assert result.causal_path[0].step == 1
        assert result.causal_path[0].node_id == step_node_id
        assert result.causal_path[0].node_type == "CustomerOrderDemand"
        assert result.causal_path[0].fact == "Order requires 50 units"


# ---------------------------------------------------------------------------
# Tests: Propagator integration — shortage → explanation auto-generated
# ---------------------------------------------------------------------------

class TestPropagatorIntegration:

    def _make_propagator(self, with_builder: bool = True):
        """Create a PropagationEngine with mocked dependencies."""
        from ootils_core.engine.orchestration.propagator import PropagationEngine

        store = MagicMock()
        traversal = MagicMock()
        dirty = MagicMock()
        calc_run_mgr = MagicMock()
        kernel = MagicMock()
        builder = ExplanationBuilder() if with_builder else None

        engine = PropagationEngine(
            store=store,
            traversal=traversal,
            dirty=dirty,
            calc_run_mgr=calc_run_mgr,
            kernel=kernel,
            explanation_builder=builder,
        )
        return engine, store, kernel, builder

    def test_no_explanation_when_no_shortage(self):
        """When has_shortage=False, ExplanationBuilder is NOT called."""
        engine, store, kernel, builder = self._make_propagator(with_builder=True)

        scenario_id = uuid4()
        node_id = uuid4()
        calc_run_id = uuid4()

        pi_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=False,
            shortage_qty=Decimal("0"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        store.get_node.return_value = pi_node
        store.get_edges_to.return_value = []
        kernel.compute_pi_node.return_value = {
            "opening_stock": Decimal("100"),
            "inflows": Decimal("0"),
            "outflows": Decimal("50"),
            "closing_stock": Decimal("50"),
            "has_shortage": False,
            "shortage_qty": Decimal("0"),
        }

        db = MagicMock()
        with patch.object(builder, "build_pi_explanation") as mock_build:
            engine._recompute_pi_node(node_id, scenario_id, calc_run_id, db)
            mock_build.assert_not_called()

    def test_explanation_generated_on_shortage(self):
        """When has_shortage=True, ExplanationBuilder.build_pi_explanation is called."""
        engine, store, kernel, builder = self._make_propagator(with_builder=True)

        scenario_id = uuid4()
        node_id = uuid4()
        calc_run_id = uuid4()

        pi_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        fresh_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        store.get_node.side_effect = [pi_node, fresh_node]
        store.get_edges_to.return_value = []

        kernel.compute_pi_node.return_value = {
            "opening_stock": Decimal("0"),
            "inflows": Decimal("0"),
            "outflows": Decimal("50"),
            "closing_stock": Decimal("-50"),
            "has_shortage": True,
            "shortage_qty": Decimal("50"),
        }

        db = MagicMock()

        mock_explanation = MagicMock(spec=Explanation)
        with patch.object(builder, "build_pi_explanation", return_value=mock_explanation) as mock_build, \
             patch.object(builder, "persist") as mock_persist:
            engine._recompute_pi_node(node_id, scenario_id, calc_run_id, db)
            mock_build.assert_called_once()
            mock_persist.assert_called_once_with(mock_explanation, db)

    def test_backward_compat_no_builder(self):
        """Without ExplanationBuilder, propagation proceeds normally (no crash)."""
        engine, store, kernel, _ = self._make_propagator(with_builder=False)

        scenario_id = uuid4()
        node_id = uuid4()
        calc_run_id = uuid4()

        pi_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        store.get_node.return_value = pi_node
        store.get_edges_to.return_value = []

        kernel.compute_pi_node.return_value = {
            "opening_stock": Decimal("0"),
            "inflows": Decimal("0"),
            "outflows": Decimal("50"),
            "closing_stock": Decimal("-50"),
            "has_shortage": True,
            "shortage_qty": Decimal("50"),
        }

        db = MagicMock()
        # Should not raise
        result = engine._recompute_pi_node(node_id, scenario_id, calc_run_id, db)
        assert isinstance(result, bool)

    def test_explanation_failure_does_not_break_propagation(self):
        """If ExplanationBuilder raises, propagation still returns normally."""
        engine, store, kernel, builder = self._make_propagator(with_builder=True)

        scenario_id = uuid4()
        node_id = uuid4()
        calc_run_id = uuid4()

        pi_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        fresh_node = make_node(
            node_type="ProjectedInventory",
            has_shortage=True,
            shortage_qty=Decimal("50"),
            time_span_start=date(2026, 4, 1),
            time_span_end=date(2026, 4, 7),
            node_id=node_id,
            scenario_id=scenario_id,
        )

        store.get_node.side_effect = [pi_node, fresh_node]
        store.get_edges_to.return_value = []

        kernel.compute_pi_node.return_value = {
            "opening_stock": Decimal("0"),
            "inflows": Decimal("0"),
            "outflows": Decimal("50"),
            "closing_stock": Decimal("-50"),
            "has_shortage": True,
            "shortage_qty": Decimal("50"),
        }

        db = MagicMock()
        with patch.object(builder, "build_pi_explanation", side_effect=RuntimeError("DB down")):
            # Should not raise — explanation failure is swallowed with a warning
            result = engine._recompute_pi_node(node_id, scenario_id, calc_run_id, db)
            assert isinstance(result, bool)


# ---------------------------------------------------------------------------
# Tests: model dataclasses
# ---------------------------------------------------------------------------

class TestExplanationModels:

    def test_causal_step_instantiation(self):
        step = CausalStep(
            step=1,
            node_id=uuid4(),
            node_type="CustomerOrderDemand",
            edge_type="consumes",
            fact="Order CO-999 requires 100 units due 2026-04-08",
        )
        assert step.step == 1
        assert step.fact

    def test_explanation_instantiation(self):
        exp = Explanation(
            explanation_id=uuid4(),
            calc_run_id=uuid4(),
            target_node_id=uuid4(),
            target_type="Shortage",
            root_cause_node_id=None,
            causal_path=[],
            summary="Test summary",
        )
        assert exp.target_type == "Shortage"
        assert exp.created_at is not None

    def test_explanation_created_at_has_timezone(self):
        exp = Explanation(
            explanation_id=uuid4(),
            calc_run_id=uuid4(),
            target_node_id=uuid4(),
            target_type="Shortage",
            root_cause_node_id=None,
            causal_path=[],
            summary="Test",
        )
        assert exp.created_at.tzinfo is not None

    def test_causal_step_nullable_fields(self):
        step = CausalStep(
            step=3,
            node_id=None,
            node_type=None,
            edge_type="governed_by",
            fact="No active substitution rule",
        )
        assert step.node_id is None
        assert step.node_type is None
