"""
mrp_run.py — level-by-level MRP summary, thin over mrp_core.

Reports the LLC-ordered planned-order picture (WO/PO counts by level, dependent
demand, top component purchase needs). Backed by mrp_core so it shares the single
demand truth (forecast consumption + proration + multi-location dedup) and the
make/buy + lot-sizing logic with the rest of the engine.

For the time-phased view (dates, lot rules, past-due) use mrp_timephased.py; for
pegging use mrp_peg.py. This is the aggregate roll-up.

Usage:
    DATABASE_URL=... python scripts/mrp_run.py [--top 20]
"""
from __future__ import annotations

import argparse
import logging
import os
import sys
import time
from collections import defaultdict

import psycopg
import mrp_core as core

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger("mrp_run")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Level-by-level MRP summary (CLI over mrp_core).")
    p.add_argument("--dsn", default=os.environ.get("DATABASE_URL"))
    p.add_argument("--horizon-days", type=int, default=540)
    p.add_argument("--top", type=int, default=20)
    p.add_argument("--allow-dev", action="store_true")
    args = p.parse_args(argv)
    if not args.dsn:
        logger.error("DATABASE_URL not set")
        return 2
    db = core.guard_db(args.dsn, args.allow_dev)
    logger.info("MRP run: DB=%s", db)

    t0 = time.perf_counter()
    with psycopg.connect(args.dsn) as conn:
        d = core.load_planning_data(conn, args.horizon_days)
    load_s = round(time.perf_counter() - t0, 2)
    gross = core.consume_demand(d)
    t1 = time.perf_counter()
    r = core.run_timephased(d, gross)
    cascade_s = round(time.perf_counter() - t1, 2)
    dependent, _ = core.peg_origins(d, gross)

    level_orders = defaultdict(lambda: [0, 0])   # llc -> [#WO, #PO]
    comp_po = []                                  # (item, qty, llc) for LLC>=1 buy
    n_wo = n_po = 0
    qty_by_item = defaultdict(float)
    kind_by_item = {}
    for item, qty, rel, need, kind, pd in r["planned"]:
        lvl = d.llc.get(item, 0)
        if kind == "WO":
            level_orders[lvl][0] += 1
            n_wo += 1
        else:
            level_orders[lvl][1] += 1
            n_po += 1
        qty_by_item[item] += qty
        kind_by_item[item] = kind
    for item, q in qty_by_item.items():
        if kind_by_item[item] == "PO" and d.llc.get(item, 0) >= 1:
            comp_po.append((item, q, d.llc.get(item, 0)))

    total_dep = sum(dependent.values())
    logger.info("=" * 84)
    logger.info("MRP RUN COMPLETE — load %.2fs + cascade %.2fs", load_s, cascade_s)
    logger.info("  Items in scope        : %d (max LLC %d)", len(d.involved), d.max_llc)
    logger.info("  Planned WORK ORDERS   : %d", n_wo)
    logger.info("  Planned PURCHASE ORD. : %d", n_po)
    logger.info("  Dependent demand generated by BOM explosion: %.0f units total", total_dep)
    logger.info("  Planned orders by level (#WO / #PO):")
    for lvl in range(0, d.max_llc + 1):
        wo, po = level_orders[lvl]
        if wo or po:
            logger.info("      LLC %-2d : %5d WO / %5d PO", lvl, wo, po)
    logger.info("=" * 84)
    comp_po.sort(key=lambda x: -x[1])
    logger.info("TOP %d component PURCHASE needs (LLC>=1, buy) — qty:", args.top)
    logger.info("  %-16s %-5s %14s", "item", "llc", "qty")
    for item, q, lvl in comp_po[: args.top]:
        logger.info("  %-16s %-5d %14.0f", d.names.get(item, str(item)[:8]), lvl, q)
    logger.info("=" * 84)
    return 0


if __name__ == "__main__":
    sys.exit(main())
