# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineStub(object):
    """============================================================================
    ootils.engine.v1 — gRPC contract between Python (FastAPI) and the Rust
    in-memory engine service (ADR-017 Architecture B).

    This is the ONLY interface between the two processes. Any new operation
    must be added here first, then implemented on both sides. Breaking
    changes follow the v1 → v2 evolution rule (new package, kept side by
    side until all clients migrate).
    ============================================================================

    -------------------------------------------------------------------- //
    Hot path — propagation + scenario lifecycle
    -------------------------------------------------------------------- //
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Propagate = channel.unary_unary(
                '/ootils.engine.v1.Engine/Propagate',
                request_serializer=engine__pb2.PropagateRequest.SerializeToString,
                response_deserializer=engine__pb2.PropagateResponse.FromString,
                _registered_method=True)
        self.ForkScenario = channel.unary_unary(
                '/ootils.engine.v1.Engine/ForkScenario',
                request_serializer=engine__pb2.ForkRequest.SerializeToString,
                response_deserializer=engine__pb2.ScenarioInfo.FromString,
                _registered_method=True)
        self.MergeScenario = channel.unary_unary(
                '/ootils.engine.v1.Engine/MergeScenario',
                request_serializer=engine__pb2.MergeRequest.SerializeToString,
                response_deserializer=engine__pb2.MergeResult.FromString,
                _registered_method=True)
        self.ListScenarios = channel.unary_unary(
                '/ootils.engine.v1.Engine/ListScenarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=engine__pb2.ScenarioList.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/ootils.engine.v1.Engine/GetNode',
                request_serializer=engine__pb2.NodeQuery.SerializeToString,
                response_deserializer=engine__pb2.NodeState.FromString,
                _registered_method=True)
        self.QueryShortages = channel.unary_stream(
                '/ootils.engine.v1.Engine/QueryShortages',
                request_serializer=engine__pb2.ShortagesQuery.SerializeToString,
                response_deserializer=engine__pb2.Shortage.FromString,
                _registered_method=True)
        self.StreamChanges = channel.unary_stream(
                '/ootils.engine.v1.Engine/StreamChanges',
                request_serializer=engine__pb2.StreamRequest.SerializeToString,
                response_deserializer=engine__pb2.ChangeEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ootils.engine.v1.Engine/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=engine__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/ootils.engine.v1.Engine/Metrics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=engine__pb2.EngineMetrics.FromString,
                _registered_method=True)


class EngineServicer(object):
    """============================================================================
    ootils.engine.v1 — gRPC contract between Python (FastAPI) and the Rust
    in-memory engine service (ADR-017 Architecture B).

    This is the ONLY interface between the two processes. Any new operation
    must be added here first, then implemented on both sides. Breaking
    changes follow the v1 → v2 evolution rule (new package, kept side by
    side until all clients migrate).
    ============================================================================

    -------------------------------------------------------------------- //
    Hot path — propagation + scenario lifecycle
    -------------------------------------------------------------------- //
    """

    def Propagate(self, request, context):
        """Propagate a single event synchronously. Returns once compute is done
        and the in-RAM state is updated. Postgres write-behind is fire-and-
        forget; the caller never waits for it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkScenario(self, request, context):
        """Fork a scenario via copy-on-write. Sub-50ms target on any profile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeScenario(self, request, context):
        """Merge a scenario's overlay back into the baseline. Atomic via arc-swap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScenarios(self, request, context):
        """List active scenarios + their memory footprint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """-------------------------------------------------------------------- //
        Reads — bypass Postgres lag, read directly from in-RAM state
        -------------------------------------------------------------------- //

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryShortages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChanges(self, request, context):
        """-------------------------------------------------------------------- //
        Real-time change stream — replaces SSE / WebSocket for the front-end
        -------------------------------------------------------------------- //

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """-------------------------------------------------------------------- //
        Operational
        -------------------------------------------------------------------- //

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Propagate': grpc.unary_unary_rpc_method_handler(
                    servicer.Propagate,
                    request_deserializer=engine__pb2.PropagateRequest.FromString,
                    response_serializer=engine__pb2.PropagateResponse.SerializeToString,
            ),
            'ForkScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkScenario,
                    request_deserializer=engine__pb2.ForkRequest.FromString,
                    response_serializer=engine__pb2.ScenarioInfo.SerializeToString,
            ),
            'MergeScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeScenario,
                    request_deserializer=engine__pb2.MergeRequest.FromString,
                    response_serializer=engine__pb2.MergeResult.SerializeToString,
            ),
            'ListScenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScenarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=engine__pb2.ScenarioList.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=engine__pb2.NodeQuery.FromString,
                    response_serializer=engine__pb2.NodeState.SerializeToString,
            ),
            'QueryShortages': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryShortages,
                    request_deserializer=engine__pb2.ShortagesQuery.FromString,
                    response_serializer=engine__pb2.Shortage.SerializeToString,
            ),
            'StreamChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChanges,
                    request_deserializer=engine__pb2.StreamRequest.FromString,
                    response_serializer=engine__pb2.ChangeEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=engine__pb2.HealthStatus.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=engine__pb2.EngineMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ootils.engine.v1.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ootils.engine.v1.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """============================================================================
    ootils.engine.v1 — gRPC contract between Python (FastAPI) and the Rust
    in-memory engine service (ADR-017 Architecture B).

    This is the ONLY interface between the two processes. Any new operation
    must be added here first, then implemented on both sides. Breaking
    changes follow the v1 → v2 evolution rule (new package, kept side by
    side until all clients migrate).
    ============================================================================

    -------------------------------------------------------------------- //
    Hot path — propagation + scenario lifecycle
    -------------------------------------------------------------------- //
    """

    @staticmethod
    def Propagate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/Propagate',
            engine__pb2.PropagateRequest.SerializeToString,
            engine__pb2.PropagateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/ForkScenario',
            engine__pb2.ForkRequest.SerializeToString,
            engine__pb2.ScenarioInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/MergeScenario',
            engine__pb2.MergeRequest.SerializeToString,
            engine__pb2.MergeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/ListScenarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            engine__pb2.ScenarioList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/GetNode',
            engine__pb2.NodeQuery.SerializeToString,
            engine__pb2.NodeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryShortages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ootils.engine.v1.Engine/QueryShortages',
            engine__pb2.ShortagesQuery.SerializeToString,
            engine__pb2.Shortage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ootils.engine.v1.Engine/StreamChanges',
            engine__pb2.StreamRequest.SerializeToString,
            engine__pb2.ChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            engine__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ootils.engine.v1.Engine/Metrics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            engine__pb2.EngineMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
